# Generated by Django 4.2.1 on 2023-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код Расход'),
        ),
        migrations.AlterField(
            model_name='consumptiondatetime',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код Дата расхода'),
        ),
        migrations.AlterField(
            model_name='format',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код Формат'),
        ),
        migrations.AlterField(
            model_name='grammage',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код Граммаж'),
        ),
        migrations.AlterField(
            model_name='incomedatetime',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код Дата поступления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код Накладная'),
        ),
        migrations.AlterField(
            model_name='k_b',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код К/Б'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код Тип сырья'),
        ),
        migrations.AlterField(
            model_name='ozm',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код ОЗМ'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код Поставщик'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_number',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код № Рулона'),
        ),
        migrations.AlterField(
            model_name='t13_050',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код 13/050'),
        ),
    ]
