# Generated by Django 4.2.1 on 2023-06-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceWithForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код Накладная')),
                ('pole1', models.CharField(max_length=255, null=True, verbose_name='Поле1')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='T13_050WithForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код 13/050')),
                ('f13_050', models.CharField(max_length=25, null=True, verbose_name='13/050')),
                ('pole1', models.IntegerField(null=True, verbose_name='Поле 1')),
                ('income_datetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.incomedatetime', verbose_name='Код Дата поступления')),
            ],
            options={
                'verbose_name': '13/050',
                'verbose_name_plural': '13/050',
            },
        ),
        migrations.CreateModel(
            name='RollWithForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=25, unique=True, verbose_name='Код № Рулона')),
                ('roll_weight', models.IntegerField(null=True, verbose_name='Вес нетто/брутто')),
                ('zone', models.CharField(max_length=25, null=True, verbose_name='Зона')),
                ('original_number', models.CharField(max_length=255, null=True, verbose_name='Исходный номер')),
                ('defect', models.CharField(max_length=25, null=True, verbose_name='Брак')),
                ('vehicle', models.CharField(max_length=255, null=True, verbose_name='Тр_средство')),
                ('input_datetime', models.DateTimeField(null=True, verbose_name='Дата/время ввода')),
                ('cert_fsc', models.CharField(max_length=255, null=True, verbose_name='Сертификат FSC')),
                ('upload_surname', models.CharField(max_length=255, null=True, verbose_name='Выгрузка Фамилия')),
                ('pole1', models.IntegerField(null=True, verbose_name='Поле1')),
                ('pole2', models.IntegerField(null=True, verbose_name='Поле2')),
                ('grammage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grammage', verbose_name='Код Граммаж')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.invoicewithforeignkey', verbose_name='Код Накладная')),
                ('k_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.k_b', verbose_name='Код К/Б')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.material', verbose_name='Код Тип сырья')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producer', verbose_name='Код Поставщик')),
                ('roll_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.format', verbose_name='Код Формат')),
            ],
            options={
                'verbose_name': 'Рулон',
                'verbose_name_plural': 'Рулоны',
            },
        ),
        migrations.CreateModel(
            name='OzmWithForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код ОЗМ')),
                ('ozm', models.CharField(max_length=25, null=True, verbose_name='ОЗМ')),
                ('grammage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grammage', verbose_name='Код Граммаж')),
                ('k_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.k_b', verbose_name='Код К/Б')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.material', verbose_name='Код Тип сырья')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producer', verbose_name='Код Поставщик')),
            ],
            options={
                'verbose_name': 'ОЗМ',
                'verbose_name_plural': 'ОЗМ',
            },
        ),
        migrations.AddField(
            model_name='invoicewithforeignkey',
            name='code13_050',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.t13_050withforeignkey', verbose_name='Код 13/050'),
        ),
        migrations.CreateModel(
            name='ConsumptionWithForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код Расход')),
                ('pole1', models.IntegerField(null=True, verbose_name='Поле1')),
                ('pole2', models.IntegerField(null=True, verbose_name='Поле2')),
                ('pole3', models.CharField(max_length=255, null=True, verbose_name='Поле3')),
                ('pole4', models.CharField(max_length=255, null=True, verbose_name='Поле4')),
                ('pole5', models.IntegerField(null=True, verbose_name='Поле5')),
                ('material_type', models.CharField(max_length=255, null=True, verbose_name='Тип сырья')),
                ('zone', models.CharField(max_length=255, null=True, verbose_name='Зона')),
                ('defect', models.CharField(max_length=255, null=True, verbose_name='Брак')),
                ('ozm', models.FloatField(null=True, verbose_name='ОЗМ')),
                ('cert_fsc', models.CharField(max_length=255, null=True, verbose_name='Сертификат FSC')),
                ('pole6', models.IntegerField(null=True, verbose_name='Поле6')),
                ('pole7', models.CharField(max_length=255, null=True, verbose_name='Поле7')),
                ('code_datetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consumptiondatetime', verbose_name='Код Дата расхода')),
                ('roll_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rollwithforeignkey', verbose_name='Код № Рулона')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расход',
            },
        ),
    ]
