# Generated by Django 4.2.1 on 2023-06-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumption',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Ozm',
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
        migrations.DeleteModel(
            name='T13_050',
        ),
    ]
